import React, { Component } from 'react';
import AccountList from './model/AccountList';



class TestAccountContainer extends Component {

    state = {
        accounts : [
            {id: '1', login:'AutogeneratedAccount1'},
            {id: '2', login:'AutogeneratedAccount2'},
            {id: '3', login:'AutogeneratedAccount3'}
        ]
    }
render() {
    return(
        <div className="TestAccountContainer">
            <AccountList accounts={this.state.accounts}/>
        </div>
    );
    }
}

export default TestAccountContainer;